################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C55_SRCS := 
A_SRCS := 
ASM_UPPER_SRCS := 
EXE_SRCS := 
LDS_UPPER_SRCS := 
CPP_SRCS := 
CMD_SRCS := 
O_SRCS := 
ELF_SRCS := 
C??_SRCS := 
C64_SRCS := 
C67_SRCS := 
SA_SRCS := 
S64_SRCS := 
OPT_SRCS := 
CXX_SRCS := 
S67_SRCS := 
S??_SRCS := 
PDE_SRCS := 
SV7A_SRCS := 
K_SRCS := 
CLA_SRCS := 
S55_SRCS := 
LD_UPPER_SRCS := 
OUT_SRCS := 
INO_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S_UPPER_SRCS := 
S43_SRCS := 
LD_SRCS := 
CMD_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
C43_SRCS := 
OBJ_SRCS := 
LDS_SRCS := 
S_SRCS := 
CC_SRCS := 
S62_SRCS := 
C62_SRCS := 
C_SRCS := 
C55_DEPS := 
C_UPPER_DEPS := 
S67_DEPS := 
S62_DEPS := 
S_DEPS := 
OPT_DEPS := 
C??_DEPS := 
ASM_UPPER_DEPS := 
S??_DEPS := 
C64_DEPS := 
CXX_DEPS := 
S64_DEPS := 
INO_DEPS := 
CLA_DEPS := 
S55_DEPS := 
SV7A_DEPS := 
EXE_OUTPUTS := 
C62_DEPS := 
C67_DEPS := 
PDE_DEPS := 
K_DEPS := 
C_DEPS := 
CC_DEPS := 
BIN_OUTPUTS := 
C++_DEPS := 
C43_DEPS := 
S43_DEPS := 
OBJS := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 
SA_DEPS := 
C++_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
S67_DEPS__QUOTED := 
C55_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
SV7A_DEPS__QUOTED := 
S??_DEPS__QUOTED := 
OBJS__QUOTED := 
C67_DEPS__QUOTED := 
K_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
INO_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
C_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
CPP_DEPS__QUOTED := 
BIN_OUTPUTS__QUOTED := 
C64_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
CLA_DEPS__QUOTED := 
S_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
S43_DEPS__QUOTED := 
EXE_OUTPUTS__QUOTED := 
S64_DEPS__QUOTED := 
S62_DEPS__QUOTED := 
PDE_DEPS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
msp430-examples-master/msp430-examples-master/00-blink \
msp430-examples-master/msp430-examples-master/01-testProject \
msp430-examples-master/msp430-examples-master/02-alternateBlink \
msp430-examples-master/msp430-examples-master/03-testSwitch \
msp430-examples-master/msp430-examples-master/04-switchToggle \
msp430-examples-master/msp430-examples-master/05-switchAlternate \
msp430-examples-master/msp430-examples-master/06-switchInterrupt \
msp430-examples-master/msp430-examples-master/07-blinkWatchdog \
msp430-examples-master/msp430-examples-master/08-charlieplexing \
msp430-examples-master/msp430-examples-master/09-charlieSwitch \
msp430-examples-master/msp430-examples-master/10-timerBlink \
msp430-examples-master/msp430-examples-master/11-sevenSegment \
msp430-examples-master/msp430-examples-master/12-sevenSegCounter \
msp430-examples-master/msp430-examples-master/13-pwmTest \
msp430-examples-master/msp430-examples-master/14-softwarePWM \
msp430-examples-master/msp430-examples-master/15-timerCapture \
msp430-examples-master/msp430-examples-master/16-adcTest \
msp430-examples-master/msp430-examples-master/17-dcoTest \
msp430-examples-master/msp430-examples-master/18-adcPWM \
msp430-examples-master/msp430-examples-master/19-adcPWM-lpm \
msp430-examples-master/msp430-examples-master/20-uartEcho \
msp430-examples-master/msp430-examples-master/21-helloWorld \
msp430-examples-master/msp430-examples-master/22-uartPrintNum \
msp430-examples-master/msp430-examples-master/23-uartADC \
msp430-examples-master/msp430-examples-master/24-spiShift \
msp430-examples-master/msp430-examples-master/25-i2cTempSensor \
msp430-examples-master/msp430-examples-master/26-bitBangShift \
msp430-examples-master/msp430-examples-master/27-helloLCD \
msp430-examples-master/msp430-examples-master/28-simpleLCD \
msp430-examples-master/msp430-examples-master/29-capTouch/Application \
msp430-examples-master/msp430-examples-master/29-capTouch/Library \
msp430-examples-master/msp430-examples-master/29-capTouch \
msp430-examples-master/msp430-examples-master/30-melodyBuzzer \

